### ISSUE TITLE
Hello author, how to correct the following mistakes

### ISSUE THREAD

**Issue by cjcu8** [JWFanggit/LOTVS-CAP#11]
D:\Program\Anaconda3\envs\py39\python.exe D:\code\LOTVS-CAP-main3\LOTVS-CAP-main\Test.py 
Traceback (most recent call last):
  File "D:\code\LOTVS-CAP-main3\LOTVS-CAP-main\Test.py", line 117, in <module>
    test_data()
  File "D:\code\LOTVS-CAP-main3\LOTVS-CAP-main\Test.py", line 94, in test_data
    num_tokens=opt.tokens
AttributeError: 'Namespace' object has no attribute 'tokens'

**Comment by JWFanggit** [comment]
Hi, just change opt.tokens to opt.num_tokens
