### ISSUE TITLE
Issue when loading the model

### ISSUE THREAD

**Issue by naxty** [JWFanggit/LOTVS-CAP#5]
Hi @JWFanggit ,

very nice project. I'm running into issues when testing the model with the uploaded weights. Are the links pointing to the right places? Thanks in advance! This would be very helpful

```
Traceback (most recent call last):
  File "/Users/user/git/insure/LOTVS-CAP/Test.py", line 120, in <module>
    test_data()
  File "/Users/user/git/insure/LOTVS-CAP/Test.py", line 108, in test_data
    model.load_state_dict(weight)
  File "/Users/user/git/insure/LOTVS-CAP/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for accident:
	Missing key(s) in state_dict: "fusion.image_model.downsampling.weight", "fusion.image_model.downsampling.bias".
	Unexpected key(s) in state_dict: "text.textNet.model.embeddings.position_ids", "fusion.text_model.model.embeddings.position_ids", "fusion.image_model.upsampling.weight", "fusion.image_model.upsampling.bias".
```

**Comment by JWFanggit** [comment]
Hi. Here's a notation error in my code. You can change downsampling to upsampling in the code and the weights file will load properly!

**Comment by Tranito** [comment]
In which files should this be changed exactly?
